# Generated by Django 5.2 on 2025-05-15 15:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_gamescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='role',
            field=models.CharField(choices=[('admin', 'Amministratore'), ('teacher', 'Insegnante'), ('student', 'Studente')], default='student', max_length=20),
        ),
    ]
