# Generated by Django 5.2 on 2025-05-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_groupmembership_joined_at_groupmembership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.TextField(blank=True),
        ),
    ]
